package com.ryx.ryxrzt.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
 *
 * @author RYX
 * @mbg.generated do_not_delete_during_merge 2019-03-20 14:56:57
 */
public class RztAgencyMould implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.AGENCY_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.RULE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.RULEREM
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String rulerem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.MOULD_NAME
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String mouldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.STATUS
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.VALIDITY_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String validityDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.CREATE_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.UPDATE_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.CREATOR
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_AGENCY_MOULD.PARENT_RULE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String parentRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.AGENCY_ID
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.AGENCY_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.AGENCY_ID
     *
     * @param agencyId the value for RYXRZT.RZT_AGENCY_MOULD.AGENCY_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setAgencyId(String agencyId) {
        this.agencyId = agencyId == null ? null : agencyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.RULE_ID
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.RULE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.RULE_ID
     *
     * @param ruleId the value for RYXRZT.RZT_AGENCY_MOULD.RULE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.RULEREM
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.RULEREM
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getRulerem() {
        return rulerem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.RULEREM
     *
     * @param rulerem the value for RYXRZT.RZT_AGENCY_MOULD.RULEREM
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setRulerem(String rulerem) {
        this.rulerem = rulerem == null ? null : rulerem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.MOULD_NAME
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.MOULD_NAME
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getMouldName() {
        return mouldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.MOULD_NAME
     *
     * @param mouldName the value for RYXRZT.RZT_AGENCY_MOULD.MOULD_NAME
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setMouldName(String mouldName) {
        this.mouldName = mouldName == null ? null : mouldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.STATUS
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.STATUS
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.STATUS
     *
     * @param status the value for RYXRZT.RZT_AGENCY_MOULD.STATUS
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.VALIDITY_DATE
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.VALIDITY_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getValidityDate() {
        return validityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.VALIDITY_DATE
     *
     * @param validityDate the value for RYXRZT.RZT_AGENCY_MOULD.VALIDITY_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setValidityDate(String validityDate) {
        this.validityDate = validityDate == null ? null : validityDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.CREATE_DATE
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.CREATE_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.CREATE_DATE
     *
     * @param createDate the value for RYXRZT.RZT_AGENCY_MOULD.CREATE_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.UPDATE_DATE
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.UPDATE_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.UPDATE_DATE
     *
     * @param updateDate the value for RYXRZT.RZT_AGENCY_MOULD.UPDATE_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.CREATOR
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.CREATOR
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.CREATOR
     *
     * @param creator the value for RYXRZT.RZT_AGENCY_MOULD.CREATOR
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_AGENCY_MOULD.PARENT_RULE_ID
     *
     * @return the value of RYXRZT.RZT_AGENCY_MOULD.PARENT_RULE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getParentRuleId() {
        return parentRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_AGENCY_MOULD.PARENT_RULE_ID
     *
     * @param parentRuleId the value for RYXRZT.RZT_AGENCY_MOULD.PARENT_RULE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setParentRuleId(String parentRuleId) {
        this.parentRuleId = parentRuleId == null ? null : parentRuleId.trim();
    }
}