package com.ryx.ryxrzt.entity;

import java.util.ArrayList;
import java.util.List;

public class RztAgencyMouldExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public RztAgencyMouldExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAgencyIdIsNull() {
            addCriterion("AGENCY_ID is null");
            return (Criteria) this;
        }

        public Criteria andAgencyIdIsNotNull() {
            addCriterion("AGENCY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAgencyIdEqualTo(String value) {
            addCriterion("AGENCY_ID =", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdNotEqualTo(String value) {
            addCriterion("AGENCY_ID <>", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdGreaterThan(String value) {
            addCriterion("AGENCY_ID >", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdGreaterThanOrEqualTo(String value) {
            addCriterion("AGENCY_ID >=", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdLessThan(String value) {
            addCriterion("AGENCY_ID <", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdLessThanOrEqualTo(String value) {
            addCriterion("AGENCY_ID <=", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdLike(String value) {
            addCriterion("AGENCY_ID like", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdNotLike(String value) {
            addCriterion("AGENCY_ID not like", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdIn(List<String> values) {
            addCriterion("AGENCY_ID in", values, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdNotIn(List<String> values) {
            addCriterion("AGENCY_ID not in", values, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdBetween(String value1, String value2) {
            addCriterion("AGENCY_ID between", value1, value2, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdNotBetween(String value1, String value2) {
            addCriterion("AGENCY_ID not between", value1, value2, "agencyId");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNull() {
            addCriterion("RULE_ID is null");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNotNull() {
            addCriterion("RULE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRuleIdEqualTo(String value) {
            addCriterion("RULE_ID =", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotEqualTo(String value) {
            addCriterion("RULE_ID <>", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThan(String value) {
            addCriterion("RULE_ID >", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThanOrEqualTo(String value) {
            addCriterion("RULE_ID >=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThan(String value) {
            addCriterion("RULE_ID <", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThanOrEqualTo(String value) {
            addCriterion("RULE_ID <=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLike(String value) {
            addCriterion("RULE_ID like", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotLike(String value) {
            addCriterion("RULE_ID not like", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdIn(List<String> values) {
            addCriterion("RULE_ID in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotIn(List<String> values) {
            addCriterion("RULE_ID not in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdBetween(String value1, String value2) {
            addCriterion("RULE_ID between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotBetween(String value1, String value2) {
            addCriterion("RULE_ID not between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleremIsNull() {
            addCriterion("RULEREM is null");
            return (Criteria) this;
        }

        public Criteria andRuleremIsNotNull() {
            addCriterion("RULEREM is not null");
            return (Criteria) this;
        }

        public Criteria andRuleremEqualTo(String value) {
            addCriterion("RULEREM =", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremNotEqualTo(String value) {
            addCriterion("RULEREM <>", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremGreaterThan(String value) {
            addCriterion("RULEREM >", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremGreaterThanOrEqualTo(String value) {
            addCriterion("RULEREM >=", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremLessThan(String value) {
            addCriterion("RULEREM <", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremLessThanOrEqualTo(String value) {
            addCriterion("RULEREM <=", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremLike(String value) {
            addCriterion("RULEREM like", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremNotLike(String value) {
            addCriterion("RULEREM not like", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremIn(List<String> values) {
            addCriterion("RULEREM in", values, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremNotIn(List<String> values) {
            addCriterion("RULEREM not in", values, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremBetween(String value1, String value2) {
            addCriterion("RULEREM between", value1, value2, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremNotBetween(String value1, String value2) {
            addCriterion("RULEREM not between", value1, value2, "rulerem");
            return (Criteria) this;
        }

        public Criteria andMouldNameIsNull() {
            addCriterion("MOULD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMouldNameIsNotNull() {
            addCriterion("MOULD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMouldNameEqualTo(String value) {
            addCriterion("MOULD_NAME =", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameNotEqualTo(String value) {
            addCriterion("MOULD_NAME <>", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameGreaterThan(String value) {
            addCriterion("MOULD_NAME >", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameGreaterThanOrEqualTo(String value) {
            addCriterion("MOULD_NAME >=", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameLessThan(String value) {
            addCriterion("MOULD_NAME <", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameLessThanOrEqualTo(String value) {
            addCriterion("MOULD_NAME <=", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameLike(String value) {
            addCriterion("MOULD_NAME like", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameNotLike(String value) {
            addCriterion("MOULD_NAME not like", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameIn(List<String> values) {
            addCriterion("MOULD_NAME in", values, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameNotIn(List<String> values) {
            addCriterion("MOULD_NAME not in", values, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameBetween(String value1, String value2) {
            addCriterion("MOULD_NAME between", value1, value2, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameNotBetween(String value1, String value2) {
            addCriterion("MOULD_NAME not between", value1, value2, "mouldName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andValidityDateIsNull() {
            addCriterion("VALIDITY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andValidityDateIsNotNull() {
            addCriterion("VALIDITY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andValidityDateEqualTo(String value) {
            addCriterion("VALIDITY_DATE =", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateNotEqualTo(String value) {
            addCriterion("VALIDITY_DATE <>", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateGreaterThan(String value) {
            addCriterion("VALIDITY_DATE >", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateGreaterThanOrEqualTo(String value) {
            addCriterion("VALIDITY_DATE >=", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateLessThan(String value) {
            addCriterion("VALIDITY_DATE <", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateLessThanOrEqualTo(String value) {
            addCriterion("VALIDITY_DATE <=", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateLike(String value) {
            addCriterion("VALIDITY_DATE like", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateNotLike(String value) {
            addCriterion("VALIDITY_DATE not like", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateIn(List<String> values) {
            addCriterion("VALIDITY_DATE in", values, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateNotIn(List<String> values) {
            addCriterion("VALIDITY_DATE not in", values, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateBetween(String value1, String value2) {
            addCriterion("VALIDITY_DATE between", value1, value2, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateNotBetween(String value1, String value2) {
            addCriterion("VALIDITY_DATE not between", value1, value2, "validityDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(String value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(String value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(String value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(String value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLike(String value) {
            addCriterion("UPDATE_DATE like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotLike(String value) {
            addCriterion("UPDATE_DATE not like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<String> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<String> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdIsNull() {
            addCriterion("PARENT_RULE_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdIsNotNull() {
            addCriterion("PARENT_RULE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdEqualTo(String value) {
            addCriterion("PARENT_RULE_ID =", value, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdNotEqualTo(String value) {
            addCriterion("PARENT_RULE_ID <>", value, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdGreaterThan(String value) {
            addCriterion("PARENT_RULE_ID >", value, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_RULE_ID >=", value, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdLessThan(String value) {
            addCriterion("PARENT_RULE_ID <", value, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdLessThanOrEqualTo(String value) {
            addCriterion("PARENT_RULE_ID <=", value, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdLike(String value) {
            addCriterion("PARENT_RULE_ID like", value, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdNotLike(String value) {
            addCriterion("PARENT_RULE_ID not like", value, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdIn(List<String> values) {
            addCriterion("PARENT_RULE_ID in", values, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdNotIn(List<String> values) {
            addCriterion("PARENT_RULE_ID not in", values, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdBetween(String value1, String value2) {
            addCriterion("PARENT_RULE_ID between", value1, value2, "parentRuleId");
            return (Criteria) this;
        }

        public Criteria andParentRuleIdNotBetween(String value1, String value2) {
            addCriterion("PARENT_RULE_ID not between", value1, value2, "parentRuleId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated do_not_delete_during_merge 2019-03-20 14:56:57
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RYXRZT.RZT_AGENCY_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}