package com.ryx.ryxrzt.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RztMouldExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public RztMouldExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRuleNumIsNull() {
            addCriterion("RULE_NUM is null");
            return (Criteria) this;
        }

        public Criteria andRuleNumIsNotNull() {
            addCriterion("RULE_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andRuleNumEqualTo(String value) {
            addCriterion("RULE_NUM =", value, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumNotEqualTo(String value) {
            addCriterion("RULE_NUM <>", value, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumGreaterThan(String value) {
            addCriterion("RULE_NUM >", value, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumGreaterThanOrEqualTo(String value) {
            addCriterion("RULE_NUM >=", value, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumLessThan(String value) {
            addCriterion("RULE_NUM <", value, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumLessThanOrEqualTo(String value) {
            addCriterion("RULE_NUM <=", value, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumLike(String value) {
            addCriterion("RULE_NUM like", value, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumNotLike(String value) {
            addCriterion("RULE_NUM not like", value, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumIn(List<String> values) {
            addCriterion("RULE_NUM in", values, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumNotIn(List<String> values) {
            addCriterion("RULE_NUM not in", values, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumBetween(String value1, String value2) {
            addCriterion("RULE_NUM between", value1, value2, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleNumNotBetween(String value1, String value2) {
            addCriterion("RULE_NUM not between", value1, value2, "ruleNum");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNull() {
            addCriterion("RULE_ID is null");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNotNull() {
            addCriterion("RULE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRuleIdEqualTo(String value) {
            addCriterion("RULE_ID =", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotEqualTo(String value) {
            addCriterion("RULE_ID <>", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThan(String value) {
            addCriterion("RULE_ID >", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThanOrEqualTo(String value) {
            addCriterion("RULE_ID >=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThan(String value) {
            addCriterion("RULE_ID <", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThanOrEqualTo(String value) {
            addCriterion("RULE_ID <=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLike(String value) {
            addCriterion("RULE_ID like", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotLike(String value) {
            addCriterion("RULE_ID not like", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdIn(List<String> values) {
            addCriterion("RULE_ID in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotIn(List<String> values) {
            addCriterion("RULE_ID not in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdBetween(String value1, String value2) {
            addCriterion("RULE_ID between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotBetween(String value1, String value2) {
            addCriterion("RULE_ID not between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdIsNull() {
            addCriterion("AGENCY_ID is null");
            return (Criteria) this;
        }

        public Criteria andAgencyIdIsNotNull() {
            addCriterion("AGENCY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAgencyIdEqualTo(String value) {
            addCriterion("AGENCY_ID =", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdNotEqualTo(String value) {
            addCriterion("AGENCY_ID <>", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdGreaterThan(String value) {
            addCriterion("AGENCY_ID >", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdGreaterThanOrEqualTo(String value) {
            addCriterion("AGENCY_ID >=", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdLessThan(String value) {
            addCriterion("AGENCY_ID <", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdLessThanOrEqualTo(String value) {
            addCriterion("AGENCY_ID <=", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdLike(String value) {
            addCriterion("AGENCY_ID like", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdNotLike(String value) {
            addCriterion("AGENCY_ID not like", value, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdIn(List<String> values) {
            addCriterion("AGENCY_ID in", values, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdNotIn(List<String> values) {
            addCriterion("AGENCY_ID not in", values, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdBetween(String value1, String value2) {
            addCriterion("AGENCY_ID between", value1, value2, "agencyId");
            return (Criteria) this;
        }

        public Criteria andAgencyIdNotBetween(String value1, String value2) {
            addCriterion("AGENCY_ID not between", value1, value2, "agencyId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdIsNull() {
            addCriterion("DEALTYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdIsNotNull() {
            addCriterion("DEALTYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdEqualTo(String value) {
            addCriterion("DEALTYPE_ID =", value, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdNotEqualTo(String value) {
            addCriterion("DEALTYPE_ID <>", value, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdGreaterThan(String value) {
            addCriterion("DEALTYPE_ID >", value, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEALTYPE_ID >=", value, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdLessThan(String value) {
            addCriterion("DEALTYPE_ID <", value, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdLessThanOrEqualTo(String value) {
            addCriterion("DEALTYPE_ID <=", value, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdLike(String value) {
            addCriterion("DEALTYPE_ID like", value, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdNotLike(String value) {
            addCriterion("DEALTYPE_ID not like", value, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdIn(List<String> values) {
            addCriterion("DEALTYPE_ID in", values, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdNotIn(List<String> values) {
            addCriterion("DEALTYPE_ID not in", values, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdBetween(String value1, String value2) {
            addCriterion("DEALTYPE_ID between", value1, value2, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andDealtypeIdNotBetween(String value1, String value2) {
            addCriterion("DEALTYPE_ID not between", value1, value2, "dealtypeId");
            return (Criteria) this;
        }

        public Criteria andSplittingModeIsNull() {
            addCriterion("SPLITTING_MODE is null");
            return (Criteria) this;
        }

        public Criteria andSplittingModeIsNotNull() {
            addCriterion("SPLITTING_MODE is not null");
            return (Criteria) this;
        }

        public Criteria andSplittingModeEqualTo(String value) {
            addCriterion("SPLITTING_MODE =", value, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeNotEqualTo(String value) {
            addCriterion("SPLITTING_MODE <>", value, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeGreaterThan(String value) {
            addCriterion("SPLITTING_MODE >", value, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeGreaterThanOrEqualTo(String value) {
            addCriterion("SPLITTING_MODE >=", value, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeLessThan(String value) {
            addCriterion("SPLITTING_MODE <", value, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeLessThanOrEqualTo(String value) {
            addCriterion("SPLITTING_MODE <=", value, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeLike(String value) {
            addCriterion("SPLITTING_MODE like", value, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeNotLike(String value) {
            addCriterion("SPLITTING_MODE not like", value, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeIn(List<String> values) {
            addCriterion("SPLITTING_MODE in", values, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeNotIn(List<String> values) {
            addCriterion("SPLITTING_MODE not in", values, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeBetween(String value1, String value2) {
            addCriterion("SPLITTING_MODE between", value1, value2, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingModeNotBetween(String value1, String value2) {
            addCriterion("SPLITTING_MODE not between", value1, value2, "splittingMode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeIsNull() {
            addCriterion("SPLITTING_REGIONMODE is null");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeIsNotNull() {
            addCriterion("SPLITTING_REGIONMODE is not null");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeEqualTo(String value) {
            addCriterion("SPLITTING_REGIONMODE =", value, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeNotEqualTo(String value) {
            addCriterion("SPLITTING_REGIONMODE <>", value, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeGreaterThan(String value) {
            addCriterion("SPLITTING_REGIONMODE >", value, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeGreaterThanOrEqualTo(String value) {
            addCriterion("SPLITTING_REGIONMODE >=", value, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeLessThan(String value) {
            addCriterion("SPLITTING_REGIONMODE <", value, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeLessThanOrEqualTo(String value) {
            addCriterion("SPLITTING_REGIONMODE <=", value, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeLike(String value) {
            addCriterion("SPLITTING_REGIONMODE like", value, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeNotLike(String value) {
            addCriterion("SPLITTING_REGIONMODE not like", value, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeIn(List<String> values) {
            addCriterion("SPLITTING_REGIONMODE in", values, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeNotIn(List<String> values) {
            addCriterion("SPLITTING_REGIONMODE not in", values, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeBetween(String value1, String value2) {
            addCriterion("SPLITTING_REGIONMODE between", value1, value2, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andSplittingRegionmodeNotBetween(String value1, String value2) {
            addCriterion("SPLITTING_REGIONMODE not between", value1, value2, "splittingRegionmode");
            return (Criteria) this;
        }

        public Criteria andRulebeginIsNull() {
            addCriterion("RULEBEGIN is null");
            return (Criteria) this;
        }

        public Criteria andRulebeginIsNotNull() {
            addCriterion("RULEBEGIN is not null");
            return (Criteria) this;
        }

        public Criteria andRulebeginEqualTo(BigDecimal value) {
            addCriterion("RULEBEGIN =", value, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRulebeginNotEqualTo(BigDecimal value) {
            addCriterion("RULEBEGIN <>", value, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRulebeginGreaterThan(BigDecimal value) {
            addCriterion("RULEBEGIN >", value, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRulebeginGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RULEBEGIN >=", value, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRulebeginLessThan(BigDecimal value) {
            addCriterion("RULEBEGIN <", value, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRulebeginLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RULEBEGIN <=", value, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRulebeginIn(List<BigDecimal> values) {
            addCriterion("RULEBEGIN in", values, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRulebeginNotIn(List<BigDecimal> values) {
            addCriterion("RULEBEGIN not in", values, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRulebeginBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RULEBEGIN between", value1, value2, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRulebeginNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RULEBEGIN not between", value1, value2, "rulebegin");
            return (Criteria) this;
        }

        public Criteria andRuleendIsNull() {
            addCriterion("RULEEND is null");
            return (Criteria) this;
        }

        public Criteria andRuleendIsNotNull() {
            addCriterion("RULEEND is not null");
            return (Criteria) this;
        }

        public Criteria andRuleendEqualTo(BigDecimal value) {
            addCriterion("RULEEND =", value, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRuleendNotEqualTo(BigDecimal value) {
            addCriterion("RULEEND <>", value, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRuleendGreaterThan(BigDecimal value) {
            addCriterion("RULEEND >", value, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRuleendGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RULEEND >=", value, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRuleendLessThan(BigDecimal value) {
            addCriterion("RULEEND <", value, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRuleendLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RULEEND <=", value, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRuleendIn(List<BigDecimal> values) {
            addCriterion("RULEEND in", values, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRuleendNotIn(List<BigDecimal> values) {
            addCriterion("RULEEND not in", values, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRuleendBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RULEEND between", value1, value2, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRuleendNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RULEEND not between", value1, value2, "ruleend");
            return (Criteria) this;
        }

        public Criteria andRulevalueIsNull() {
            addCriterion("RULEVALUE is null");
            return (Criteria) this;
        }

        public Criteria andRulevalueIsNotNull() {
            addCriterion("RULEVALUE is not null");
            return (Criteria) this;
        }

        public Criteria andRulevalueEqualTo(BigDecimal value) {
            addCriterion("RULEVALUE =", value, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andRulevalueNotEqualTo(BigDecimal value) {
            addCriterion("RULEVALUE <>", value, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andRulevalueGreaterThan(BigDecimal value) {
            addCriterion("RULEVALUE >", value, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andRulevalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RULEVALUE >=", value, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andRulevalueLessThan(BigDecimal value) {
            addCriterion("RULEVALUE <", value, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andRulevalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RULEVALUE <=", value, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andRulevalueIn(List<BigDecimal> values) {
            addCriterion("RULEVALUE in", values, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andRulevalueNotIn(List<BigDecimal> values) {
            addCriterion("RULEVALUE not in", values, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andRulevalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RULEVALUE between", value1, value2, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andRulevalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RULEVALUE not between", value1, value2, "rulevalue");
            return (Criteria) this;
        }

        public Criteria andValidityDateIsNull() {
            addCriterion("VALIDITY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andValidityDateIsNotNull() {
            addCriterion("VALIDITY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andValidityDateEqualTo(String value) {
            addCriterion("VALIDITY_DATE =", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateNotEqualTo(String value) {
            addCriterion("VALIDITY_DATE <>", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateGreaterThan(String value) {
            addCriterion("VALIDITY_DATE >", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateGreaterThanOrEqualTo(String value) {
            addCriterion("VALIDITY_DATE >=", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateLessThan(String value) {
            addCriterion("VALIDITY_DATE <", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateLessThanOrEqualTo(String value) {
            addCriterion("VALIDITY_DATE <=", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateLike(String value) {
            addCriterion("VALIDITY_DATE like", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateNotLike(String value) {
            addCriterion("VALIDITY_DATE not like", value, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateIn(List<String> values) {
            addCriterion("VALIDITY_DATE in", values, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateNotIn(List<String> values) {
            addCriterion("VALIDITY_DATE not in", values, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateBetween(String value1, String value2) {
            addCriterion("VALIDITY_DATE between", value1, value2, "validityDate");
            return (Criteria) this;
        }

        public Criteria andValidityDateNotBetween(String value1, String value2) {
            addCriterion("VALIDITY_DATE not between", value1, value2, "validityDate");
            return (Criteria) this;
        }

        public Criteria andCreateidIsNull() {
            addCriterion("CREATEID is null");
            return (Criteria) this;
        }

        public Criteria andCreateidIsNotNull() {
            addCriterion("CREATEID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateidEqualTo(String value) {
            addCriterion("CREATEID =", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotEqualTo(String value) {
            addCriterion("CREATEID <>", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidGreaterThan(String value) {
            addCriterion("CREATEID >", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEID >=", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidLessThan(String value) {
            addCriterion("CREATEID <", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidLessThanOrEqualTo(String value) {
            addCriterion("CREATEID <=", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidLike(String value) {
            addCriterion("CREATEID like", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotLike(String value) {
            addCriterion("CREATEID not like", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidIn(List<String> values) {
            addCriterion("CREATEID in", values, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotIn(List<String> values) {
            addCriterion("CREATEID not in", values, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidBetween(String value1, String value2) {
            addCriterion("CREATEID between", value1, value2, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotBetween(String value1, String value2) {
            addCriterion("CREATEID not between", value1, value2, "createid");
            return (Criteria) this;
        }

        public Criteria andCreatedtIsNull() {
            addCriterion("CREATEDT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedtIsNotNull() {
            addCriterion("CREATEDT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedtEqualTo(String value) {
            addCriterion("CREATEDT =", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotEqualTo(String value) {
            addCriterion("CREATEDT <>", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtGreaterThan(String value) {
            addCriterion("CREATEDT >", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEDT >=", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLessThan(String value) {
            addCriterion("CREATEDT <", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLessThanOrEqualTo(String value) {
            addCriterion("CREATEDT <=", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLike(String value) {
            addCriterion("CREATEDT like", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotLike(String value) {
            addCriterion("CREATEDT not like", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtIn(List<String> values) {
            addCriterion("CREATEDT in", values, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotIn(List<String> values) {
            addCriterion("CREATEDT not in", values, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtBetween(String value1, String value2) {
            addCriterion("CREATEDT between", value1, value2, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotBetween(String value1, String value2) {
            addCriterion("CREATEDT not between", value1, value2, "createdt");
            return (Criteria) this;
        }

        public Criteria andRuleremIsNull() {
            addCriterion("RULEREM is null");
            return (Criteria) this;
        }

        public Criteria andRuleremIsNotNull() {
            addCriterion("RULEREM is not null");
            return (Criteria) this;
        }

        public Criteria andRuleremEqualTo(String value) {
            addCriterion("RULEREM =", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremNotEqualTo(String value) {
            addCriterion("RULEREM <>", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremGreaterThan(String value) {
            addCriterion("RULEREM >", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremGreaterThanOrEqualTo(String value) {
            addCriterion("RULEREM >=", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremLessThan(String value) {
            addCriterion("RULEREM <", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremLessThanOrEqualTo(String value) {
            addCriterion("RULEREM <=", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremLike(String value) {
            addCriterion("RULEREM like", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremNotLike(String value) {
            addCriterion("RULEREM not like", value, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremIn(List<String> values) {
            addCriterion("RULEREM in", values, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremNotIn(List<String> values) {
            addCriterion("RULEREM not in", values, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremBetween(String value1, String value2) {
            addCriterion("RULEREM between", value1, value2, "rulerem");
            return (Criteria) this;
        }

        public Criteria andRuleremNotBetween(String value1, String value2) {
            addCriterion("RULEREM not between", value1, value2, "rulerem");
            return (Criteria) this;
        }

        public Criteria andMouldNameIsNull() {
            addCriterion("MOULD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMouldNameIsNotNull() {
            addCriterion("MOULD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMouldNameEqualTo(String value) {
            addCriterion("MOULD_NAME =", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameNotEqualTo(String value) {
            addCriterion("MOULD_NAME <>", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameGreaterThan(String value) {
            addCriterion("MOULD_NAME >", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameGreaterThanOrEqualTo(String value) {
            addCriterion("MOULD_NAME >=", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameLessThan(String value) {
            addCriterion("MOULD_NAME <", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameLessThanOrEqualTo(String value) {
            addCriterion("MOULD_NAME <=", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameLike(String value) {
            addCriterion("MOULD_NAME like", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameNotLike(String value) {
            addCriterion("MOULD_NAME not like", value, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameIn(List<String> values) {
            addCriterion("MOULD_NAME in", values, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameNotIn(List<String> values) {
            addCriterion("MOULD_NAME not in", values, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameBetween(String value1, String value2) {
            addCriterion("MOULD_NAME between", value1, value2, "mouldName");
            return (Criteria) this;
        }

        public Criteria andMouldNameNotBetween(String value1, String value2) {
            addCriterion("MOULD_NAME not between", value1, value2, "mouldName");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNull() {
            addCriterion("BATCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNotNull() {
            addCriterion("BATCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBatchIdEqualTo(String value) {
            addCriterion("BATCH_ID =", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotEqualTo(String value) {
            addCriterion("BATCH_ID <>", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThan(String value) {
            addCriterion("BATCH_ID >", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("BATCH_ID >=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThan(String value) {
            addCriterion("BATCH_ID <", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThanOrEqualTo(String value) {
            addCriterion("BATCH_ID <=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLike(String value) {
            addCriterion("BATCH_ID like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotLike(String value) {
            addCriterion("BATCH_ID not like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdIn(List<String> values) {
            addCriterion("BATCH_ID in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotIn(List<String> values) {
            addCriterion("BATCH_ID not in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdBetween(String value1, String value2) {
            addCriterion("BATCH_ID between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotBetween(String value1, String value2) {
            addCriterion("BATCH_ID not between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIsNull() {
            addCriterion("MODIFY_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIsNotNull() {
            addCriterion("MODIFY_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTypeEqualTo(String value) {
            addCriterion("MODIFY_TYPE =", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeNotEqualTo(String value) {
            addCriterion("MODIFY_TYPE <>", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeGreaterThan(String value) {
            addCriterion("MODIFY_TYPE >", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_TYPE >=", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeLessThan(String value) {
            addCriterion("MODIFY_TYPE <", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_TYPE <=", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeLike(String value) {
            addCriterion("MODIFY_TYPE like", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeNotLike(String value) {
            addCriterion("MODIFY_TYPE not like", value, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIn(List<String> values) {
            addCriterion("MODIFY_TYPE in", values, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeNotIn(List<String> values) {
            addCriterion("MODIFY_TYPE not in", values, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeBetween(String value1, String value2) {
            addCriterion("MODIFY_TYPE between", value1, value2, "modifyType");
            return (Criteria) this;
        }

        public Criteria andModifyTypeNotBetween(String value1, String value2) {
            addCriterion("MODIFY_TYPE not between", value1, value2, "modifyType");
            return (Criteria) this;
        }

        public Criteria andDelayIsNull() {
            addCriterion("DELAY is null");
            return (Criteria) this;
        }

        public Criteria andDelayIsNotNull() {
            addCriterion("DELAY is not null");
            return (Criteria) this;
        }

        public Criteria andDelayEqualTo(String value) {
            addCriterion("DELAY =", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotEqualTo(String value) {
            addCriterion("DELAY <>", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayGreaterThan(String value) {
            addCriterion("DELAY >", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayGreaterThanOrEqualTo(String value) {
            addCriterion("DELAY >=", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayLessThan(String value) {
            addCriterion("DELAY <", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayLessThanOrEqualTo(String value) {
            addCriterion("DELAY <=", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayLike(String value) {
            addCriterion("DELAY like", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotLike(String value) {
            addCriterion("DELAY not like", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayIn(List<String> values) {
            addCriterion("DELAY in", values, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotIn(List<String> values) {
            addCriterion("DELAY not in", values, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayBetween(String value1, String value2) {
            addCriterion("DELAY between", value1, value2, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotBetween(String value1, String value2) {
            addCriterion("DELAY not between", value1, value2, "delay");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIsNull() {
            addCriterion("SEQUENCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIsNotNull() {
            addCriterion("SEQUENCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceIdEqualTo(String value) {
            addCriterion("SEQUENCE_ID =", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotEqualTo(String value) {
            addCriterion("SEQUENCE_ID <>", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdGreaterThan(String value) {
            addCriterion("SEQUENCE_ID >", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdGreaterThanOrEqualTo(String value) {
            addCriterion("SEQUENCE_ID >=", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdLessThan(String value) {
            addCriterion("SEQUENCE_ID <", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdLessThanOrEqualTo(String value) {
            addCriterion("SEQUENCE_ID <=", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdLike(String value) {
            addCriterion("SEQUENCE_ID like", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotLike(String value) {
            addCriterion("SEQUENCE_ID not like", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIn(List<String> values) {
            addCriterion("SEQUENCE_ID in", values, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotIn(List<String> values) {
            addCriterion("SEQUENCE_ID not in", values, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdBetween(String value1, String value2) {
            addCriterion("SEQUENCE_ID between", value1, value2, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotBetween(String value1, String value2) {
            addCriterion("SEQUENCE_ID not between", value1, value2, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdIsNull() {
            addCriterion("RULE_NAME_ID is null");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdIsNotNull() {
            addCriterion("RULE_NAME_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdEqualTo(String value) {
            addCriterion("RULE_NAME_ID =", value, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdNotEqualTo(String value) {
            addCriterion("RULE_NAME_ID <>", value, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdGreaterThan(String value) {
            addCriterion("RULE_NAME_ID >", value, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdGreaterThanOrEqualTo(String value) {
            addCriterion("RULE_NAME_ID >=", value, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdLessThan(String value) {
            addCriterion("RULE_NAME_ID <", value, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdLessThanOrEqualTo(String value) {
            addCriterion("RULE_NAME_ID <=", value, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdLike(String value) {
            addCriterion("RULE_NAME_ID like", value, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdNotLike(String value) {
            addCriterion("RULE_NAME_ID not like", value, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdIn(List<String> values) {
            addCriterion("RULE_NAME_ID in", values, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdNotIn(List<String> values) {
            addCriterion("RULE_NAME_ID not in", values, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdBetween(String value1, String value2) {
            addCriterion("RULE_NAME_ID between", value1, value2, "ruleNameId");
            return (Criteria) this;
        }

        public Criteria andRuleNameIdNotBetween(String value1, String value2) {
            addCriterion("RULE_NAME_ID not between", value1, value2, "ruleNameId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated do_not_delete_during_merge 2019-03-20 14:56:57
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}