package com.ryx.ryxrzt.entity;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table RYXRZT.RZT_MOULD
 *
 * @mbg.generated do_not_delete_during_merge 2019-03-20 14:56:57
 */
public class RztMould implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.RULE_NUM
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String ruleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.RULE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.AGENCY_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.DEALTYPE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String dealtypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.SPLITTING_MODE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String splittingMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.SPLITTING_REGIONMODE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String splittingRegionmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.RULEBEGIN
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private BigDecimal rulebegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.RULEEND
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private BigDecimal ruleend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.RULEVALUE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private BigDecimal rulevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.VALIDITY_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String validityDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.CREATEID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String createid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.CREATEDT
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String createdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.RULEREM
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String rulerem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.MOULD_NAME
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String mouldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.BATCH_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.MODIFY_TYPE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String modifyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.DELAY
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String delay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.SEQUENCE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String sequenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RYXRZT.RZT_MOULD.RULE_NAME_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private String ruleNameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RYXRZT.RZT_MOULD
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.RULE_NUM
     *
     * @return the value of RYXRZT.RZT_MOULD.RULE_NUM
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getRuleNum() {
        return ruleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.RULE_NUM
     *
     * @param ruleNum the value for RYXRZT.RZT_MOULD.RULE_NUM
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setRuleNum(String ruleNum) {
        this.ruleNum = ruleNum == null ? null : ruleNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.RULE_ID
     *
     * @return the value of RYXRZT.RZT_MOULD.RULE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.RULE_ID
     *
     * @param ruleId the value for RYXRZT.RZT_MOULD.RULE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.AGENCY_ID
     *
     * @return the value of RYXRZT.RZT_MOULD.AGENCY_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.AGENCY_ID
     *
     * @param agencyId the value for RYXRZT.RZT_MOULD.AGENCY_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setAgencyId(String agencyId) {
        this.agencyId = agencyId == null ? null : agencyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.DEALTYPE_ID
     *
     * @return the value of RYXRZT.RZT_MOULD.DEALTYPE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getDealtypeId() {
        return dealtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.DEALTYPE_ID
     *
     * @param dealtypeId the value for RYXRZT.RZT_MOULD.DEALTYPE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setDealtypeId(String dealtypeId) {
        this.dealtypeId = dealtypeId == null ? null : dealtypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.SPLITTING_MODE
     *
     * @return the value of RYXRZT.RZT_MOULD.SPLITTING_MODE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getSplittingMode() {
        return splittingMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.SPLITTING_MODE
     *
     * @param splittingMode the value for RYXRZT.RZT_MOULD.SPLITTING_MODE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setSplittingMode(String splittingMode) {
        this.splittingMode = splittingMode == null ? null : splittingMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.SPLITTING_REGIONMODE
     *
     * @return the value of RYXRZT.RZT_MOULD.SPLITTING_REGIONMODE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getSplittingRegionmode() {
        return splittingRegionmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.SPLITTING_REGIONMODE
     *
     * @param splittingRegionmode the value for RYXRZT.RZT_MOULD.SPLITTING_REGIONMODE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setSplittingRegionmode(String splittingRegionmode) {
        this.splittingRegionmode = splittingRegionmode == null ? null : splittingRegionmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.RULEBEGIN
     *
     * @return the value of RYXRZT.RZT_MOULD.RULEBEGIN
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public BigDecimal getRulebegin() {
        return rulebegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.RULEBEGIN
     *
     * @param rulebegin the value for RYXRZT.RZT_MOULD.RULEBEGIN
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setRulebegin(BigDecimal rulebegin) {
        this.rulebegin = rulebegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.RULEEND
     *
     * @return the value of RYXRZT.RZT_MOULD.RULEEND
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public BigDecimal getRuleend() {
        return ruleend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.RULEEND
     *
     * @param ruleend the value for RYXRZT.RZT_MOULD.RULEEND
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setRuleend(BigDecimal ruleend) {
        this.ruleend = ruleend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.RULEVALUE
     *
     * @return the value of RYXRZT.RZT_MOULD.RULEVALUE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public BigDecimal getRulevalue() {
        return rulevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.RULEVALUE
     *
     * @param rulevalue the value for RYXRZT.RZT_MOULD.RULEVALUE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setRulevalue(BigDecimal rulevalue) {
        this.rulevalue = rulevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.VALIDITY_DATE
     *
     * @return the value of RYXRZT.RZT_MOULD.VALIDITY_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getValidityDate() {
        return validityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.VALIDITY_DATE
     *
     * @param validityDate the value for RYXRZT.RZT_MOULD.VALIDITY_DATE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setValidityDate(String validityDate) {
        this.validityDate = validityDate == null ? null : validityDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.CREATEID
     *
     * @return the value of RYXRZT.RZT_MOULD.CREATEID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.CREATEID
     *
     * @param createid the value for RYXRZT.RZT_MOULD.CREATEID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setCreateid(String createid) {
        this.createid = createid == null ? null : createid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.CREATEDT
     *
     * @return the value of RYXRZT.RZT_MOULD.CREATEDT
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getCreatedt() {
        return createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.CREATEDT
     *
     * @param createdt the value for RYXRZT.RZT_MOULD.CREATEDT
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setCreatedt(String createdt) {
        this.createdt = createdt == null ? null : createdt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.RULEREM
     *
     * @return the value of RYXRZT.RZT_MOULD.RULEREM
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getRulerem() {
        return rulerem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.RULEREM
     *
     * @param rulerem the value for RYXRZT.RZT_MOULD.RULEREM
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setRulerem(String rulerem) {
        this.rulerem = rulerem == null ? null : rulerem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.MOULD_NAME
     *
     * @return the value of RYXRZT.RZT_MOULD.MOULD_NAME
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getMouldName() {
        return mouldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.MOULD_NAME
     *
     * @param mouldName the value for RYXRZT.RZT_MOULD.MOULD_NAME
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setMouldName(String mouldName) {
        this.mouldName = mouldName == null ? null : mouldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.BATCH_ID
     *
     * @return the value of RYXRZT.RZT_MOULD.BATCH_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.BATCH_ID
     *
     * @param batchId the value for RYXRZT.RZT_MOULD.BATCH_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.MODIFY_TYPE
     *
     * @return the value of RYXRZT.RZT_MOULD.MODIFY_TYPE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getModifyType() {
        return modifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.MODIFY_TYPE
     *
     * @param modifyType the value for RYXRZT.RZT_MOULD.MODIFY_TYPE
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setModifyType(String modifyType) {
        this.modifyType = modifyType == null ? null : modifyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.DELAY
     *
     * @return the value of RYXRZT.RZT_MOULD.DELAY
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getDelay() {
        return delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.DELAY
     *
     * @param delay the value for RYXRZT.RZT_MOULD.DELAY
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setDelay(String delay) {
        this.delay = delay == null ? null : delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.SEQUENCE_ID
     *
     * @return the value of RYXRZT.RZT_MOULD.SEQUENCE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getSequenceId() {
        return sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.SEQUENCE_ID
     *
     * @param sequenceId the value for RYXRZT.RZT_MOULD.SEQUENCE_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setSequenceId(String sequenceId) {
        this.sequenceId = sequenceId == null ? null : sequenceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RYXRZT.RZT_MOULD.RULE_NAME_ID
     *
     * @return the value of RYXRZT.RZT_MOULD.RULE_NAME_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public String getRuleNameId() {
        return ruleNameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RYXRZT.RZT_MOULD.RULE_NAME_ID
     *
     * @param ruleNameId the value for RYXRZT.RZT_MOULD.RULE_NAME_ID
     *
     * @mbg.generated 2019-03-20 14:56:57
     */
    public void setRuleNameId(String ruleNameId) {
        this.ruleNameId = ruleNameId == null ? null : ruleNameId.trim();
    }
}